# use of different method in list 
marks=[]
m1=int(input("enter marks of 1"))
marks.append(m1)
m2=int(input("enter marks of 2"))
marks.append(m2)
m3=int(input("enter marks of 3"))
marks.append(m3)
m4=int(input("enter marks of 4"))
marks.append(m4)
m5=int(input("enter marks of 5"))
marks.append(m5)
m6=int(input("enter marks of 6"))
marks.append(m6)
marks.sort()
print(marks)
print(marks[1])
marks.reverse()
print(marks)
print(marks[1])
marks.insert(2,18)
print(marks)
marks.pop(2)
print(marks)